// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function MakeRequest(arg1:string,arg2:string,arg3:Array<main.Header>,arg4:Array<main.Query>,arg5:string):Promise<main.Response>;
