// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWS(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWS'](arg1, arg2, arg3);
}

export function MakeRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MakeRequest'](arg1, arg2, arg3, arg4, arg5);
}
