// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HTTP(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['HTTP'](arg1, arg2, arg3, arg4, arg5);
}

export function WS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WS'](arg1, arg2, arg3, arg4);
}
